[package]
name = "oxiphant"
version = "0.1.0"
edition = "2021"
description = "A PHP subset compiler written in Rust (oxidizing elephant)"
authors = ["abbychau"]

[dependencies]
lazy_static = "1.4.0"
regex = "1.10.2"
thiserror = "1.0.50"

